# configuration document: https://cloud.google.com/appengine/docs/

env: standard
runtime: nodejs16
service: darius-ui

handlers:
  - url: /.*
    secure: always
    script: auto

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20
  
liveness_check:
  path: "/_health"
  check_interval_sec: 120
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
