# configuration document: https://cloud.google.com/appengine/docs/

env: standard
runtime: nodejs16
service: default

handlers:
  - url: /.*
    secure: always
    script: auto

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10
  
liveness_check:
  path: "/_health"
  check_interval_sec: 120
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

automatic_scaling:
  max_instances: 2
  min_instances: 0
  max_concurrent_requests: 30
  min_pending_latency: "500ms"
  max_idle_instances: 1
  min_idle_instances: 0
